server:
  port: 8001
spring:
  application:
    name: business-account-book
  #数据库连接配置
  datasource:
    #数据库连接
    url: jdbc:mysql://192.168.79.135:3306/account_book?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    #用户名密码
    username: root
    password: Ai1314520..
    #驱动包
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:com/api/mapper/**/*.xml
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/